spring:
  datasource:
    url: jdbc:h2:mem:rolecraft
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

rolecraft:
  ats:
    required-weight: 0.5
    preferred-weight: 0.3
    experience-weight: 0.2

  openai:
  api-key: ${OPENAI_API_KEY}
  url: https://api.openai.com/v1/chat/completions
